# Generated by Django 5.1.5 on 2026-03-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='author/pfp/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
